### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by KasonWan** [catx-feitu/Coze-Discord-Bridge#1]
![image](https://github.com/catx-feitu/Coze-Discord-Bridge/assets/58059719/36f99d28-4b94-4ad3-8cb1-33455d17caf1)

**Comment by KasonWan** [comment]
![image](https://github.com/catx-feitu/Coze-Discord-Bridge/assets/58059719/005940cf-3351-4f7b-b95f-bdae44659596)

**Comment by catx-feitu** [comment]
可以提供一下更加完整的日志信息吗 以及使用的系统

**Comment by KasonWan** [comment]
> 可以提供一下更加完整的日志信息吗 以及使用的系统

![image](https://github.com/catx-feitu/Coze-Discord-Bridge/assets/58059719/54710be0-1b63-4d78-8bc9-820019a73b46)
CentOS 7.9的系统

**Comment by KasonWan** [comment]
> > 可以提供一下更加完整的日志信息吗 以及使用的系统
> 
> ![image](https://private-user-images.githubusercontent.com/58059719/301482951-54710be0-1b63-4d78-8bc9-820019a73b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTMyMDgsIm5iZiI6MTcwNjc5MjkwOCwicGF0aCI6Ii81ODA1OTcxOS8zMDE0ODI5NTEtNTQ3MTBiZTAtMWI2My00ZDc4LThiYzktODIwMDE5YTczYjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTI3NmE1YjkzMjdjOTQyZDY4YzliMjc2N2FjMDI4MDdlOTA2MTU0ODA4ODFjZTc2NWE2NTRkNzdlOWMzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5o6iBKFtvY8bUTyFkTYV07BxUankWvwjx4RtMPzN6U) CentOS 7.9的系统

jdk版本问题

**Comment by KasonWan** [comment]
![image](https://github.com/catx-feitu/Coze-Discord-Bridge/assets/58059719/8b2f5142-1e55-4965-a5d0-27335fc1eeb6)
还是报错

**Comment by catx-feitu** [comment]
> > > 可以提供一下更加完整的日志信息吗 以及使用的系统
> > 
> > ![image](https://private-user-images.githubusercontent.com/58059719/301482951-54710be0-1b63-4d78-8bc9-820019a73b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTMyMDgsIm5iZiI6MTcwNjc5MjkwOCwicGF0aCI6Ii81ODA1OTcxOS8zMDE0ODI5NTEtNTQ3MTBiZTAtMWI2My00ZDc4LThiYzktODIwMDE5YTczYjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTI3NmE1YjkzMjdjOTQyZDY4YzliMjc2N2FjMDI4MDdlOTA2MTU0ODA4ODFjZTc2NWE2NTRkNzdlOWMzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5o6iBKFtvY8bUTyFkTYV07BxUankWvwjx4RtMPzN6U) CentOS 7.9的系统
> 
> jdk版本问题，jdk8用不了，使用17正常

emm 确实 感谢反馈

之后会在README.md中添加jdk版本信息

**Comment by KasonWan** [comment]
> > > > 可以提供一下更加完整的日志信息吗 以及使用的系统
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/58059719/301482951-54710be0-1b63-4d78-8bc9-820019a73b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTMyMDgsIm5iZiI6MTcwNjc5MjkwOCwicGF0aCI6Ii81ODA1OTcxOS8zMDE0ODI5NTEtNTQ3MTBiZTAtMWI2My00ZDc4LThiYzktODIwMDE5YTczYjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTI3NmE1YjkzMjdjOTQyZDY4YzliMjc2N2FjMDI4MDdlOTA2MTU0ODA4ODFjZTc2NWE2NTRkNzdlOWMzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5o6iBKFtvY8bUTyFkTYV07BxUankWvwjx4RtMPzN6U) CentOS 7.9的系统
> > 
> > 
> > jdk版本问题，jdk8用不了，使用17正常
> 
> emm 确实 感谢反馈
> 
> 之后会在README.md中添加jdk版本信息

![image](https://github.com/catx-feitu/Coze-Discord-Bridge/assets/58059719/13993f22-7fa7-400a-bea6-80440609b355)
如何关闭https呢

**Comment by catx-feitu** [comment]
> > > > > 可以提供一下更加完整的日志信息吗 以及使用的系统
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/58059719/301482951-54710be0-1b63-4d78-8bc9-820019a73b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTMyMDgsIm5iZiI6MTcwNjc5MjkwOCwicGF0aCI6Ii81ODA1OTcxOS8zMDE0ODI5NTEtNTQ3MTBiZTAtMWI2My00ZDc4LThiYzktODIwMDE5YTczYjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTI3NmE1YjkzMjdjOTQyZDY4YzliMjc2N2FjMDI4MDdlOTA2MTU0ODA4ODFjZTc2NWE2NTRkNzdlOWMzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5o6iBKFtvY8bUTyFkTYV07BxUankWvwjx4RtMPzN6U) CentOS 7.9的系统
> > > 
> > > 
> > > jdk版本问题，jdk8用不了，使用17正常
> > 
> > emm 确实 感谢反馈
> > 
> > 之后会在README.md中添加jdk版本信息
> 
> ![image](https://github.com/catx-feitu/Coze-Discord-Bridge/assets/58059719/13993f22-7fa7-400a-bea6-80440609b355)
> 如何关闭https呢

目前暂时没办法关闭 或者是让HTTPS监听失败(暂时可以把端口设置成0临时解决(我没试过 但应该可以))

这个版本中只会在HTTP和HTTPS都监听失败时才会启动失败

下个版本会添加关闭

**Comment by KasonWan** [comment]
> > > > > > 可以提供一下更加完整的日志信息吗 以及使用的系统
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/58059719/301482951-54710be0-1b63-4d78-8bc9-820019a73b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTMyMDgsIm5iZiI6MTcwNjc5MjkwOCwicGF0aCI6Ii81ODA1OTcxOS8zMDE0ODI5NTEtNTQ3MTBiZTAtMWI2My00ZDc4LThiYzktODIwMDE5YTczYjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTI3NmE1YjkzMjdjOTQyZDY4YzliMjc2N2FjMDI4MDdlOTA2MTU0ODA4ODFjZTc2NWE2NTRkNzdlOWMzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5o6iBKFtvY8bUTyFkTYV07BxUankWvwjx4RtMPzN6U) CentOS 7.9的系统
> > > > 
> > > > 
> > > > jdk版本问题，jdk8用不了，使用17正常
> > > 
> > > 
> > > emm 确实 感谢反馈
> > > 之后会在README.md中添加jdk版本信息
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/58059719/301524733-13993f22-7fa7-400a-bea6-80440609b355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTY2NzcsIm5iZiI6MTcwNjc5NjM3NywicGF0aCI6Ii81ODA1OTcxOS8zMDE1MjQ3MzMtMTM5OTNmMjItN2ZhNy00MDBhLWJlYTYtODA0NDA2MDliMzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE0MDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOGJhZTVhZDE1NGY3OTAwMjY4NGZjNzc5ODg1ODQwNTM3MDgwMjgxZmJmNGYxZDY0ZTdmZmQwZDhiYTdhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q0fxUllhW6XqkG2tVHI8WR-iDzZ1sdmQkYGEtfMl35M)
> > 如何关闭https呢
> 
> 目前暂时没办法关闭 或者是让HTTPS监听失败(暂时可以把端口设置成0临时解决(我没试过 但应该可以))
> 
> 这个版本中只会在HTTP和HTTPS都监听失败时才会启动失败
> 
> 下个版本会添加关闭

![image](https://github.com/catx-feitu/Coze-Discord-Bridge/assets/58059719/42dbc67a-660c-4328-bb1d-85c6365f8a0f)
这个一直卡在这，不知道咋回事

**Comment by catx-feitu** [comment]
> > > > > > > 可以提供一下更加完整的日志信息吗 以及使用的系统
> > > > > > 
> > > > > > 
> > > > > > ![image](https://private-user-images.githubusercontent.com/58059719/301482951-54710be0-1b63-4d78-8bc9-820019a73b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTMyMDgsIm5iZiI6MTcwNjc5MjkwOCwicGF0aCI6Ii81ODA1OTcxOS8zMDE0ODI5NTEtNTQ3MTBiZTAtMWI2My00ZDc4LThiYzktODIwMDE5YTczYjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTI3NmE1YjkzMjdjOTQyZDY4YzliMjc2N2FjMDI4MDdlOTA2MTU0ODA4ODFjZTc2NWE2NTRkNzdlOWMzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5o6iBKFtvY8bUTyFkTYV07BxUankWvwjx4RtMPzN6U) CentOS 7.9的系统
> > > > > 
> > > > > 
> > > > > jdk版本问题，jdk8用不了，使用17正常
> > > > 
> > > > 
> > > > emm 确实 感谢反馈
> > > > 之后会在README.md中添加jdk版本信息
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/58059719/301524733-13993f22-7fa7-400a-bea6-80440609b355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTY2NzcsIm5iZiI6MTcwNjc5NjM3NywicGF0aCI6Ii81ODA1OTcxOS8zMDE1MjQ3MzMtMTM5OTNmMjItN2ZhNy00MDBhLWJlYTYtODA0NDA2MDliMzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE0MDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOGJhZTVhZDE1NGY3OTAwMjY4NGZjNzc5ODg1ODQwNTM3MDgwMjgxZmJmNGYxZDY0ZTdmZmQwZDhiYTdhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q0fxUllhW6XqkG2tVHI8WR-iDzZ1sdmQkYGEtfMl35M)
> > > 如何关闭https呢
> > 
> > 
> > 目前暂时没办法关闭 或者是让HTTPS监听失败(暂时可以把端口设置成0临时解决(我没试过 但应该可以))
> > 这个版本中只会在HTTP和HTTPS都监听失败时才会启动失败
> > 下个版本会添加关闭
> 
> ![image](https://private-user-images.githubusercontent.com/58059719/301531952-158afcb3-fd1f-47d6-81f5-5f8f2db8f547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzAyOTgsIm5iZiI6MTcwNzA2OTk5OCwicGF0aCI6Ii81ODA1OTcxOS8zMDE1MzE5NTItMTU4YWZjYjMtZmQxZi00N2Q2LTgxZjUtNWY4ZjJkYjhmNTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE4MDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMzEyMWRiZDY5YWM4NTIxZDdhMzA2OWRhNTc3ZGI1Mzg5MWJiMTZhZDNkN2I3ZjBjMWU1OTAwYzhlYzExYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xlfSd1sptqz--86qKlnILX-hKphKDhsPwwZRn7H6KM0) 这是啥问题

HTTPS需要证书 注意是jks格式的 不是pem格式
[生成密钥库](https://cloud.tencent.com/developer/article/2129597)
[将PEK导入JKS](https://cloud.tencent.com/developer/ask/sof/1394199)
