### ISSUE TITLE
java.io.FileNotFoundException: keystore.jks (No such file or directory)

### ISSUE THREAD

**Issue by yxnwh** [catx-feitu/Coze-Discord-Bridge#3]
不知道啥原因？
```
[11:32:46] [main/INFO]: 加载配置成功
[11:32:46] [main/INFO]: [default] 开始登录流程..
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[11:32:47] [WritingThread/INFO]: Websocket closed with reason 'Authentication failed.' and code AUTHENTICATION_FAILED (4004) by server!
[11:32:47] [main/ERROR]: [default] 初始化失败
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
at catx.feitu.coze_discord_bridge.api.CozeGPT.Login(CozeGPT.java:64) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at catx.feitu.coze_discord_bridge.api.CozeGPT.(CozeGPT.java:49) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at catx.feitu.coze_discord_bridge.GPTManage.newGPT(GPTManage.java:22) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at catx.feitu.coze_discord_bridge.Main.main(Main.java:71) [CozeDiscordBridge-1.0.0213-all.jar:?]
Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:660) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:527) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3713) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
[11:32:48] [main/ERROR]: java.lang.Exception: 配置中的所有Bot配置均加载失败
```
![image](https://github.com/catx-feitu/Coze-Discord-Bridge/assets/36069159/e0be82b0-bea6-4bee-9032-8c98316cb404)

**Comment by yxnwh** [comment]
> 不知道啥原因？
> 
> ```
> [11:32:46] [main/INFO]: 加载配置成功
> [11:32:46] [main/INFO]: [default] 开始登录流程..
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> [11:32:47] [WritingThread/INFO]: Websocket closed with reason 'Authentication failed.' and code AUTHENTICATION_FAILED (4004) by server!
> [11:32:47] [main/ERROR]: [default] 初始化失败
> java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
> at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
> at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
> at catx.feitu.coze_discord_bridge.api.CozeGPT.Login(CozeGPT.java:64) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at catx.feitu.coze_discord_bridge.api.CozeGPT.(CozeGPT.java:49) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at catx.feitu.coze_discord_bridge.GPTManage.newGPT(GPTManage.java:22) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at catx.feitu.coze_discord_bridge.Main.main(Main.java:71) [CozeDiscordBridge-1.0.0213-all.jar:?]
> Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
> at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:660) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
> at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
> at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
> at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
> at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:527) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3713) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> [11:32:48] [main/ERROR]: java.lang.Exception: 配置中的所有Bot配置均加载失败
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/36069159/305711404-e0be82b0-bea6-4bee-9032-8c98316cb404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTcxODMsIm5iZiI6MTcwODI1Njg4MywicGF0aCI6Ii8zNjA2OTE1OS8zMDU3MTE0MDQtZTBiZTgyYjAtYmVhNi00YmVlLTkwMzItOGM5ODMxNmNiNDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDExNDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDFlNzQ2ZDc1YmFjYzkyYzUyYWVhZmNiN2JkNDk2ZDUyZjAzMjY0Njg4MGNhMDBjYzRmZDA1NDIwYmM0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kf0M19NoffqCWVR_qQvkQDZBm2v_vuO9zgDXeRFT4yM)

弄错了bot的token，换上后ok了，但是又出现了新的问题。。。
```
[11:48:50] [main/INFO]: 加载配置成功
[11:48:50] [main/INFO]: [default] 开始登录流程..
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[11:48:52] [main/INFO]: [default] 初始化成功
[11:48:52] [main/INFO]: 初始化线程池成功 最大线程:10
[11:48:52] [main/INFO]: 监听HTTP服务 0.0.0.0:8092 成功
[11:48:52] [main/ERROR]: 监听HTTPS服务 0.0.0.0:8093 失败
 java.io.FileNotFoundException: keystore.jks (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:111) ~[?:?]
	at catx.feitu.coze_discord_bridge.HttpServer.HttpServerManage.start(HttpServerManage.java:76) [CozeDiscordBridge-1.0.0213-all.jar:?]
	at catx.feitu.coze_discord_bridge.Main.main(Main.java:81) [CozeDiscordBridge-1.0.0213-all.jar:?]
```

**Comment by catx-feitu** [comment]
> > 不知道啥原因？
> > ```
> > [11:32:46] [main/INFO]: 加载配置成功
> > [11:32:46] [main/INFO]: [default] 开始登录流程..
> > WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> > [11:32:47] [WritingThread/INFO]: Websocket closed with reason 'Authentication failed.' and code AUTHENTICATION_FAILED (4004) by server!
> > [11:32:47] [main/ERROR]: [default] 初始化失败
> > java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
> > at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
> > at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
> > at catx.feitu.coze_discord_bridge.api.CozeGPT.Login(CozeGPT.java:64) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at catx.feitu.coze_discord_bridge.api.CozeGPT.(CozeGPT.java:49) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at catx.feitu.coze_discord_bridge.GPTManage.newGPT(GPTManage.java:22) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at catx.feitu.coze_discord_bridge.Main.main(Main.java:71) [CozeDiscordBridge-1.0.0213-all.jar:?]
> > Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
> > at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:660) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
> > at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
> > at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
> > at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
> > at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:527) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3713) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > [11:32:48] [main/ERROR]: java.lang.Exception: 配置中的所有Bot配置均加载失败
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/36069159/305711404-e0be82b0-bea6-4bee-9032-8c98316cb404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTcxODMsIm5iZiI6MTcwODI1Njg4MywicGF0aCI6Ii8zNjA2OTE1OS8zMDU3MTE0MDQtZTBiZTgyYjAtYmVhNi00YmVlLTkwMzItOGM5ODMxNmNiNDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDExNDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDFlNzQ2ZDc1YmFjYzkyYzUyYWVhZmNiN2JkNDk2ZDUyZjAzMjY0Njg4MGNhMDBjYzRmZDA1NDIwYmM0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kf0M19NoffqCWVR_qQvkQDZBm2v_vuO9zgDXeRFT4yM)
> 
> 弄错了bot的token，换上后ok了，但是又出现了新的问题。。。
> 
> ```
> [11:48:50] [main/INFO]: 加载配置成功
> [11:48:50] [main/INFO]: [default] 开始登录流程..
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> [11:48:52] [main/INFO]: [default] 初始化成功
> [11:48:52] [main/INFO]: 初始化线程池成功 最大线程:10
> [11:48:52] [main/INFO]: 监听HTTP服务 0.0.0.0:8092 成功
> [11:48:52] [main/ERROR]: 监听HTTPS服务 0.0.0.0:8093 失败
>  java.io.FileNotFoundException: keystore.jks (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method) ~[?:?]
> 	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
> 	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
> 	at java.io.FileInputStream.<init>(FileInputStream.java:111) ~[?:?]
> 	at catx.feitu.coze_discord_bridge.HttpServer.HttpServerManage.start(HttpServerManage.java:76) [CozeDiscordBridge-1.0.0213-all.jar:?]
> 	at catx.feitu.coze_discord_bridge.Main.main(Main.java:81) [CozeDiscordBridge-1.0.0213-all.jar:?]
> ```

根据你的错误信息来看

问题出在HTTPS监听上

HTTPS监听需要自己配置密钥 ( #1 中提到过)

如果用不到可以直接在配置文件中关闭HTTPS

**Comment by yxnwh** [comment]
> > > 不知道啥原因？
> > > ```
> > > [11:32:46] [main/INFO]: 加载配置成功
> > > [11:32:46] [main/INFO]: [default] 开始登录流程..
> > > WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> > > [11:32:47] [WritingThread/INFO]: Websocket closed with reason 'Authentication failed.' and code AUTHENTICATION_FAILED (4004) by server!
> > > [11:32:47] [main/ERROR]: [default] 初始化失败
> > > java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
> > > at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
> > > at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
> > > at catx.feitu.coze_discord_bridge.api.CozeGPT.Login(CozeGPT.java:64) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at catx.feitu.coze_discord_bridge.api.CozeGPT.(CozeGPT.java:49) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at catx.feitu.coze_discord_bridge.GPTManage.newGPT(GPTManage.java:22) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at catx.feitu.coze_discord_bridge.Main.main(Main.java:71) [CozeDiscordBridge-1.0.0213-all.jar:?]
> > > Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
> > > at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:660) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
> > > at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
> > > at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
> > > at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
> > > at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:527) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3713) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[CozeDiscordBridge-1.0.0213-all.jar:?]
> > > [11:32:48] [main/ERROR]: java.lang.Exception: 配置中的所有Bot配置均加载失败
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![image](https://private-user-images.githubusercontent.com/36069159/305711404-e0be82b0-bea6-4bee-9032-8c98316cb404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTcxODMsIm5iZiI6MTcwODI1Njg4MywicGF0aCI6Ii8zNjA2OTE1OS8zMDU3MTE0MDQtZTBiZTgyYjAtYmVhNi00YmVlLTkwMzItOGM5ODMxNmNiNDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDExNDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDFlNzQ2ZDc1YmFjYzkyYzUyYWVhZmNiN2JkNDk2ZDUyZjAzMjY0Njg4MGNhMDBjYzRmZDA1NDIwYmM0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kf0M19NoffqCWVR_qQvkQDZBm2v_vuO9zgDXeRFT4yM)
> > 
> > 
> > 弄错了bot的token，换上后ok了，但是又出现了新的问题。。。
> > ```
> > [11:48:50] [main/INFO]: 加载配置成功
> > [11:48:50] [main/INFO]: [default] 开始登录流程..
> > WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> > [11:48:52] [main/INFO]: [default] 初始化成功
> > [11:48:52] [main/INFO]: 初始化线程池成功 最大线程:10
> > [11:48:52] [main/INFO]: 监听HTTP服务 0.0.0.0:8092 成功
> > [11:48:52] [main/ERROR]: 监听HTTPS服务 0.0.0.0:8093 失败
> >  java.io.FileNotFoundException: keystore.jks (No such file or directory)
> > 	at java.io.FileInputStream.open0(Native Method) ~[?:?]
> > 	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
> > 	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
> > 	at java.io.FileInputStream.<init>(FileInputStream.java:111) ~[?:?]
> > 	at catx.feitu.coze_discord_bridge.HttpServer.HttpServerManage.start(HttpServerManage.java:76) [CozeDiscordBridge-1.0.0213-all.jar:?]
> > 	at catx.feitu.coze_discord_bridge.Main.main(Main.java:81) [CozeDiscordBridge-1.0.0213-all.jar:?]
> > ```
> 
> 根据你的错误信息来看
> 
> 问题出在HTTPS监听上
> 
> HTTPS监听需要自己配置密钥 ( #1 中提到过)
> 
> 如果用不到可以直接在配置文件中关闭HTTPS

确实，https设置为0后，问题解决
还是按照大佬发的jks生成教程老老实实的生成下，一劳永逸，😄
